apiVersion: azure.microsoft.com/v1alpha1
kind: RedisCache
metadata:
  name: azure-vote-redis
spec:
  location: westeurope
  resourceGroup: azure-vote-rg
  properties:
    sku:
      name: Basic
      family: C
      capacity: 1
    enableNonSslPort: true
