# Creates a RG
apiVersion: azure.microsoft.com/v1alpha1
kind: ResourceGroup
metadata:
  name: sample-rg
spec:
  location: westeurope
---
# Creates a Storage Account
apiVersion: azure.microsoft.com/v1alpha1
kind: StorageAccount
metadata:
  name: sample0sa024337
spec:
  location: westeurope
  resourceGroup: sample-rg 
  sku:
    name: Standard_LRS
  kind: StorageV2
  accessTier: Hot
  supportsHttpsTrafficOnly: true
